/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_jnidemo_util_JniUtil */

#ifndef _Included_com_android_jnidemo_util_JniUtil
#define _Included_com_android_jnidemo_util_JniUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_android_jnidemo_util_JniUtil
 * Method:    print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_android_jnidemo_util_JniUtil_print
  (JNIEnv *, jclass);

/*
 * Class:     com_android_jnidemo_util_JniUtil
 * Method:    getStringFromC
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_android_jnidemo_util_JniUtil_getStringFromC
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_android_jnidemo_util_JniUtil
 * Method:    sumArray
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_com_android_jnidemo_util_JniUtil_sumArray
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     com_android_jnidemo_util_JniUtil
 * Method:    initInt2Darray
 * Signature: (I)[[I
 */
JNIEXPORT jobjectArray JNICALL Java_com_android_jnidemo_util_JniUtil_initInt2Darray
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_android_jnidemo_util_JniUtil
 * Method:    accessField
 * Signature: (Lcom/android/jnidemo/util/Demo;)V
 */
JNIEXPORT void JNICALL Java_com_android_jnidemo_util_JniUtil_accessField
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
